### ISSUE TITLE
Criar tabela para armazenar os dados do processo do SEI

### ISSUE THREAD

**Issue by jorgeluizjr** [culturagovbr/SisTel#2]
Criar table TB_ALOCACAO_SEI , campos (ID_ALOCACAO_SEI, ID_ALOCACAO_USUARIO_LINHA (TB_ALOCACAO_USUARIO_LINHA), ID_RESUMO (TB_RESUMO), PROCESSO_SEI (VARCHAR), RESSARCIMENTO (BOOLEAN)

**Comment by volthier** [comment]
Conforme requisitado e necessidade do sistema foi acrescentada tabela para tramite e vínculos referenciados ao Sistema SEI.
